/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnfahrtRouteImport } from './routes/anfahrt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as HonorareRouteImport } from './routes/honorare'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeitfaedenRouteImport } from './routes/leitfaeden'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen/index'
import { Route as LeistungenBeratungRouteImport } from './routes/leistungen/beratung'
import { Route as LeistungenInhouseRouteImport } from './routes/leistungen/inhouse'
import { Route as LeistungenKonzepteRouteImport } from './routes/leistungen/konzepte'
import { Route as LeistungenTalkRouteImport } from './routes/leistungen/talk'
import { Route as PraxisbriefAbmeldenRouteImport } from './routes/praxisbrief/abmelden'
import { Route as PraxisbriefBestaetigenRouteImport } from './routes/praxisbrief/bestaetigen'
import { Route as PraxisbriefeIndexRouteImport } from './routes/praxisbriefe/index'
import { Route as PraxisbriefeSlugRouteImport } from './routes/praxisbriefe/$slug'
import { Route as SeminareTermineRouteImport } from './routes/seminare/termine'
import { Route as AuthenticatedVerwaltungIndexRouteImport } from './routes/_authenticated/verwaltung/index'
import { Route as AuthenticatedVerwaltungAnfragenRouteImport } from './routes/_authenticated/verwaltung/anfragen'
import { Route as AuthenticatedVerwaltungAnmeldungenRouteImport } from './routes/_authenticated/verwaltung/anmeldungen'
import { Route as AuthenticatedVerwaltungTermineRouteImport } from './routes/_authenticated/verwaltung/termine'
import { Route as LeistungenSeminareIndexRouteImport } from './routes/leistungen/seminare/index'
import { Route as LeistungenSeminareSlugRouteImport } from './routes/leistungen/seminare/$slug'
import { Route as LeistungenSeminareFuehrenMitZielenRouteImport } from './routes/leistungen/seminare/fuehren-mit-zielen'
import { Route as LeistungenSeminareKraftDerWertschaetzungRouteImport } from './routes/leistungen/seminare/kraft-der-wertschaetzung'
import { Route as LeistungenSeminareModerationWorkshopsRouteImport } from './routes/leistungen/seminare/moderation-workshops'
import { Route as LeistungenSeminareZeitEffektivitaetRouteImport } from './routes/leistungen/seminare/zeit-effektivitaet'
import { Route as AuthenticatedVerwaltungTeilnehmerTerminIdRouteImport } from './routes/_authenticated/verwaltung/teilnehmer.$terminId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnfahrtRoute = AnfahrtRouteImport.update({
  id: '/anfahrt',
  path: '/anfahrt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorareRoute = HonorareRouteImport.update({
  id: '/honorare',
  path: '/honorare',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeitfaedenRoute = LeitfaedenRouteImport.update({
  id: '/leitfaeden',
  path: '/leitfaeden',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenBeratungRoute = LeistungenBeratungRouteImport.update({
  id: '/leistungen/beratung',
  path: '/leistungen/beratung',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenInhouseRoute = LeistungenInhouseRouteImport.update({
  id: '/leistungen/inhouse',
  path: '/leistungen/inhouse',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenKonzepteRoute = LeistungenKonzepteRouteImport.update({
  id: '/leistungen/konzepte',
  path: '/leistungen/konzepte',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenTalkRoute = LeistungenTalkRouteImport.update({
  id: '/leistungen/talk',
  path: '/leistungen/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisbriefAbmeldenRoute = PraxisbriefAbmeldenRouteImport.update({
  id: '/praxisbrief/abmelden',
  path: '/praxisbrief/abmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisbriefBestaetigenRoute = PraxisbriefBestaetigenRouteImport.update({
  id: '/praxisbrief/bestaetigen',
  path: '/praxisbrief/bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisbriefeIndexRoute = PraxisbriefeIndexRouteImport.update({
  id: '/praxisbriefe/',
  path: '/praxisbriefe/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisbriefeSlugRoute = PraxisbriefeSlugRouteImport.update({
  id: '/praxisbriefe/$slug',
  path: '/praxisbriefe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminareTermineRoute = SeminareTermineRouteImport.update({
  id: '/seminare/termine',
  path: '/seminare/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerwaltungIndexRoute =
  AuthenticatedVerwaltungIndexRouteImport.update({
    id: '/verwaltung/',
    path: '/verwaltung/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerwaltungAnfragenRoute =
  AuthenticatedVerwaltungAnfragenRouteImport.update({
    id: '/verwaltung/anfragen',
    path: '/verwaltung/anfragen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerwaltungAnmeldungenRoute =
  AuthenticatedVerwaltungAnmeldungenRouteImport.update({
    id: '/verwaltung/anmeldungen',
    path: '/verwaltung/anmeldungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerwaltungTermineRoute =
  AuthenticatedVerwaltungTermineRouteImport.update({
    id: '/verwaltung/termine',
    path: '/verwaltung/termine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LeistungenSeminareIndexRoute = LeistungenSeminareIndexRouteImport.update({
  id: '/leistungen/seminare/',
  path: '/leistungen/seminare/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSeminareSlugRoute = LeistungenSeminareSlugRouteImport.update({
  id: '/leistungen/seminare/$slug',
  path: '/leistungen/seminare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSeminareFuehrenMitZielenRoute =
  LeistungenSeminareFuehrenMitZielenRouteImport.update({
    id: '/leistungen/seminare/fuehren-mit-zielen',
    path: '/leistungen/seminare/fuehren-mit-zielen',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenSeminareKraftDerWertschaetzungRoute =
  LeistungenSeminareKraftDerWertschaetzungRouteImport.update({
    id: '/leistungen/seminare/kraft-der-wertschaetzung',
    path: '/leistungen/seminare/kraft-der-wertschaetzung',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenSeminareModerationWorkshopsRoute =
  LeistungenSeminareModerationWorkshopsRouteImport.update({
    id: '/leistungen/seminare/moderation-workshops',
    path: '/leistungen/seminare/moderation-workshops',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeistungenSeminareZeitEffektivitaetRoute =
  LeistungenSeminareZeitEffektivitaetRouteImport.update({
    id: '/leistungen/seminare/zeit-effektivitaet',
    path: '/leistungen/seminare/zeit-effektivitaet',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVerwaltungTeilnehmerTerminIdRoute =
  AuthenticatedVerwaltungTeilnehmerTerminIdRouteImport.update({
    id: '/verwaltung/teilnehmer/$terminId',
    path: '/verwaltung/teilnehmer/$terminId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anfahrt': typeof AnfahrtRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/honorare': typeof HonorareRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leitfaeden': typeof LeitfaedenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/leistungen/beratung': typeof LeistungenBeratungRoute
  '/leistungen/inhouse': typeof LeistungenInhouseRoute
  '/leistungen/konzepte': typeof LeistungenKonzepteRoute
  '/leistungen/talk': typeof LeistungenTalkRoute
  '/praxisbrief/abmelden': typeof PraxisbriefAbmeldenRoute
  '/praxisbrief/bestaetigen': typeof PraxisbriefBestaetigenRoute
  '/praxisbriefe/$slug': typeof PraxisbriefeSlugRoute
  '/seminare/termine': typeof SeminareTermineRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/praxisbriefe/': typeof PraxisbriefeIndexRoute
  '/verwaltung/anfragen': typeof AuthenticatedVerwaltungAnfragenRoute
  '/verwaltung/anmeldungen': typeof AuthenticatedVerwaltungAnmeldungenRoute
  '/verwaltung/termine': typeof AuthenticatedVerwaltungTermineRoute
  '/leistungen/seminare/$slug': typeof LeistungenSeminareSlugRoute
  '/leistungen/seminare/fuehren-mit-zielen': typeof LeistungenSeminareFuehrenMitZielenRoute
  '/leistungen/seminare/kraft-der-wertschaetzung': typeof LeistungenSeminareKraftDerWertschaetzungRoute
  '/leistungen/seminare/moderation-workshops': typeof LeistungenSeminareModerationWorkshopsRoute
  '/leistungen/seminare/zeit-effektivitaet': typeof LeistungenSeminareZeitEffektivitaetRoute
  '/verwaltung/': typeof AuthenticatedVerwaltungIndexRoute
  '/leistungen/seminare/': typeof LeistungenSeminareIndexRoute
  '/verwaltung/teilnehmer/$terminId': typeof AuthenticatedVerwaltungTeilnehmerTerminIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anfahrt': typeof AnfahrtRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/honorare': typeof HonorareRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leitfaeden': typeof LeitfaedenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/leistungen/beratung': typeof LeistungenBeratungRoute
  '/leistungen/inhouse': typeof LeistungenInhouseRoute
  '/leistungen/konzepte': typeof LeistungenKonzepteRoute
  '/leistungen/talk': typeof LeistungenTalkRoute
  '/praxisbrief/abmelden': typeof PraxisbriefAbmeldenRoute
  '/praxisbrief/bestaetigen': typeof PraxisbriefBestaetigenRoute
  '/praxisbriefe/$slug': typeof PraxisbriefeSlugRoute
  '/seminare/termine': typeof SeminareTermineRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/praxisbriefe': typeof PraxisbriefeIndexRoute
  '/verwaltung/anfragen': typeof AuthenticatedVerwaltungAnfragenRoute
  '/verwaltung/anmeldungen': typeof AuthenticatedVerwaltungAnmeldungenRoute
  '/verwaltung/termine': typeof AuthenticatedVerwaltungTermineRoute
  '/leistungen/seminare/$slug': typeof LeistungenSeminareSlugRoute
  '/leistungen/seminare/fuehren-mit-zielen': typeof LeistungenSeminareFuehrenMitZielenRoute
  '/leistungen/seminare/kraft-der-wertschaetzung': typeof LeistungenSeminareKraftDerWertschaetzungRoute
  '/leistungen/seminare/moderation-workshops': typeof LeistungenSeminareModerationWorkshopsRoute
  '/leistungen/seminare/zeit-effektivitaet': typeof LeistungenSeminareZeitEffektivitaetRoute
  '/verwaltung': typeof AuthenticatedVerwaltungIndexRoute
  '/leistungen/seminare': typeof LeistungenSeminareIndexRoute
  '/verwaltung/teilnehmer/$terminId': typeof AuthenticatedVerwaltungTeilnehmerTerminIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/anfahrt': typeof AnfahrtRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/honorare': typeof HonorareRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leitfaeden': typeof LeitfaedenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-mich': typeof UeberMichRoute
  '/leistungen/beratung': typeof LeistungenBeratungRoute
  '/leistungen/inhouse': typeof LeistungenInhouseRoute
  '/leistungen/konzepte': typeof LeistungenKonzepteRoute
  '/leistungen/talk': typeof LeistungenTalkRoute
  '/praxisbrief/abmelden': typeof PraxisbriefAbmeldenRoute
  '/praxisbrief/bestaetigen': typeof PraxisbriefBestaetigenRoute
  '/praxisbriefe/$slug': typeof PraxisbriefeSlugRoute
  '/seminare/termine': typeof SeminareTermineRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/praxisbriefe/': typeof PraxisbriefeIndexRoute
  '/_authenticated/verwaltung/anfragen': typeof AuthenticatedVerwaltungAnfragenRoute
  '/_authenticated/verwaltung/anmeldungen': typeof AuthenticatedVerwaltungAnmeldungenRoute
  '/_authenticated/verwaltung/termine': typeof AuthenticatedVerwaltungTermineRoute
  '/leistungen/seminare/$slug': typeof LeistungenSeminareSlugRoute
  '/leistungen/seminare/fuehren-mit-zielen': typeof LeistungenSeminareFuehrenMitZielenRoute
  '/leistungen/seminare/kraft-der-wertschaetzung': typeof LeistungenSeminareKraftDerWertschaetzungRoute
  '/leistungen/seminare/moderation-workshops': typeof LeistungenSeminareModerationWorkshopsRoute
  '/leistungen/seminare/zeit-effektivitaet': typeof LeistungenSeminareZeitEffektivitaetRoute
  '/_authenticated/verwaltung/': typeof AuthenticatedVerwaltungIndexRoute
  '/leistungen/seminare/': typeof LeistungenSeminareIndexRoute
  '/_authenticated/verwaltung/teilnehmer/$terminId': typeof AuthenticatedVerwaltungTeilnehmerTerminIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anfahrt'
    | '/auth'
    | '/datenschutz'
    | '/honorare'
    | '/impressum'
    | '/kontakt'
    | '/leitfaeden'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/leistungen/beratung'
    | '/leistungen/inhouse'
    | '/leistungen/konzepte'
    | '/leistungen/talk'
    | '/praxisbrief/abmelden'
    | '/praxisbrief/bestaetigen'
    | '/praxisbriefe/$slug'
    | '/seminare/termine'
    | '/leistungen/'
    | '/praxisbriefe/'
    | '/verwaltung/anfragen'
    | '/verwaltung/anmeldungen'
    | '/verwaltung/termine'
    | '/leistungen/seminare/$slug'
    | '/leistungen/seminare/fuehren-mit-zielen'
    | '/leistungen/seminare/kraft-der-wertschaetzung'
    | '/leistungen/seminare/moderation-workshops'
    | '/leistungen/seminare/zeit-effektivitaet'
    | '/verwaltung/'
    | '/leistungen/seminare/'
    | '/verwaltung/teilnehmer/$terminId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anfahrt'
    | '/auth'
    | '/datenschutz'
    | '/honorare'
    | '/impressum'
    | '/kontakt'
    | '/leitfaeden'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/leistungen/beratung'
    | '/leistungen/inhouse'
    | '/leistungen/konzepte'
    | '/leistungen/talk'
    | '/praxisbrief/abmelden'
    | '/praxisbrief/bestaetigen'
    | '/praxisbriefe/$slug'
    | '/seminare/termine'
    | '/leistungen'
    | '/praxisbriefe'
    | '/verwaltung/anfragen'
    | '/verwaltung/anmeldungen'
    | '/verwaltung/termine'
    | '/leistungen/seminare/$slug'
    | '/leistungen/seminare/fuehren-mit-zielen'
    | '/leistungen/seminare/kraft-der-wertschaetzung'
    | '/leistungen/seminare/moderation-workshops'
    | '/leistungen/seminare/zeit-effektivitaet'
    | '/verwaltung'
    | '/leistungen/seminare'
    | '/verwaltung/teilnehmer/$terminId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/anfahrt'
    | '/auth'
    | '/datenschutz'
    | '/honorare'
    | '/impressum'
    | '/kontakt'
    | '/leitfaeden'
    | '/sitemap.xml'
    | '/ueber-mich'
    | '/leistungen/beratung'
    | '/leistungen/inhouse'
    | '/leistungen/konzepte'
    | '/leistungen/talk'
    | '/praxisbrief/abmelden'
    | '/praxisbrief/bestaetigen'
    | '/praxisbriefe/$slug'
    | '/seminare/termine'
    | '/leistungen/'
    | '/praxisbriefe/'
    | '/_authenticated/verwaltung/anfragen'
    | '/_authenticated/verwaltung/anmeldungen'
    | '/_authenticated/verwaltung/termine'
    | '/leistungen/seminare/$slug'
    | '/leistungen/seminare/fuehren-mit-zielen'
    | '/leistungen/seminare/kraft-der-wertschaetzung'
    | '/leistungen/seminare/moderation-workshops'
    | '/leistungen/seminare/zeit-effektivitaet'
    | '/_authenticated/verwaltung/'
    | '/leistungen/seminare/'
    | '/_authenticated/verwaltung/teilnehmer/$terminId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AnfahrtRoute: typeof AnfahrtRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  HonorareRoute: typeof HonorareRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeitfaedenRoute: typeof LeitfaedenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberMichRoute: typeof UeberMichRoute
  LeistungenBeratungRoute: typeof LeistungenBeratungRoute
  LeistungenInhouseRoute: typeof LeistungenInhouseRoute
  LeistungenKonzepteRoute: typeof LeistungenKonzepteRoute
  LeistungenTalkRoute: typeof LeistungenTalkRoute
  PraxisbriefAbmeldenRoute: typeof PraxisbriefAbmeldenRoute
  PraxisbriefBestaetigenRoute: typeof PraxisbriefBestaetigenRoute
  PraxisbriefeSlugRoute: typeof PraxisbriefeSlugRoute
  SeminareTermineRoute: typeof SeminareTermineRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
  PraxisbriefeIndexRoute: typeof PraxisbriefeIndexRoute
  LeistungenSeminareSlugRoute: typeof LeistungenSeminareSlugRoute
  LeistungenSeminareFuehrenMitZielenRoute: typeof LeistungenSeminareFuehrenMitZielenRoute
  LeistungenSeminareKraftDerWertschaetzungRoute: typeof LeistungenSeminareKraftDerWertschaetzungRoute
  LeistungenSeminareModerationWorkshopsRoute: typeof LeistungenSeminareModerationWorkshopsRoute
  LeistungenSeminareZeitEffektivitaetRoute: typeof LeistungenSeminareZeitEffektivitaetRoute
  LeistungenSeminareIndexRoute: typeof LeistungenSeminareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anfahrt': {
      id: '/anfahrt'
      path: '/anfahrt'
      fullPath: '/anfahrt'
      preLoaderRoute: typeof AnfahrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honorare': {
      id: '/honorare'
      path: '/honorare'
      fullPath: '/honorare'
      preLoaderRoute: typeof HonorareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitfaeden': {
      id: '/leitfaeden'
      path: '/leitfaeden'
      fullPath: '/leitfaeden'
      preLoaderRoute: typeof LeitfaedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/beratung': {
      id: '/leistungen/beratung'
      path: '/leistungen/beratung'
      fullPath: '/leistungen/beratung'
      preLoaderRoute: typeof LeistungenBeratungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/inhouse': {
      id: '/leistungen/inhouse'
      path: '/leistungen/inhouse'
      fullPath: '/leistungen/inhouse'
      preLoaderRoute: typeof LeistungenInhouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/konzepte': {
      id: '/leistungen/konzepte'
      path: '/leistungen/konzepte'
      fullPath: '/leistungen/konzepte'
      preLoaderRoute: typeof LeistungenKonzepteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/talk': {
      id: '/leistungen/talk'
      path: '/leistungen/talk'
      fullPath: '/leistungen/talk'
      preLoaderRoute: typeof LeistungenTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxisbrief/abmelden': {
      id: '/praxisbrief/abmelden'
      path: '/praxisbrief/abmelden'
      fullPath: '/praxisbrief/abmelden'
      preLoaderRoute: typeof PraxisbriefAbmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxisbrief/bestaetigen': {
      id: '/praxisbrief/bestaetigen'
      path: '/praxisbrief/bestaetigen'
      fullPath: '/praxisbrief/bestaetigen'
      preLoaderRoute: typeof PraxisbriefBestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxisbriefe/': {
      id: '/praxisbriefe/'
      path: '/praxisbriefe'
      fullPath: '/praxisbriefe/'
      preLoaderRoute: typeof PraxisbriefeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxisbriefe/$slug': {
      id: '/praxisbriefe/$slug'
      path: '/praxisbriefe/$slug'
      fullPath: '/praxisbriefe/$slug'
      preLoaderRoute: typeof PraxisbriefeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminare/termine': {
      id: '/seminare/termine'
      path: '/seminare/termine'
      fullPath: '/seminare/termine'
      preLoaderRoute: typeof SeminareTermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verwaltung/': {
      id: '/_authenticated/verwaltung/'
      path: '/verwaltung'
      fullPath: '/verwaltung/'
      preLoaderRoute: typeof AuthenticatedVerwaltungIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verwaltung/anfragen': {
      id: '/_authenticated/verwaltung/anfragen'
      path: '/verwaltung/anfragen'
      fullPath: '/verwaltung/anfragen'
      preLoaderRoute: typeof AuthenticatedVerwaltungAnfragenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verwaltung/anmeldungen': {
      id: '/_authenticated/verwaltung/anmeldungen'
      path: '/verwaltung/anmeldungen'
      fullPath: '/verwaltung/anmeldungen'
      preLoaderRoute: typeof AuthenticatedVerwaltungAnmeldungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verwaltung/termine': {
      id: '/_authenticated/verwaltung/termine'
      path: '/verwaltung/termine'
      fullPath: '/verwaltung/termine'
      preLoaderRoute: typeof AuthenticatedVerwaltungTermineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/leistungen/seminare/': {
      id: '/leistungen/seminare/'
      path: '/leistungen/seminare'
      fullPath: '/leistungen/seminare/'
      preLoaderRoute: typeof LeistungenSeminareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/seminare/$slug': {
      id: '/leistungen/seminare/$slug'
      path: '/leistungen/seminare/$slug'
      fullPath: '/leistungen/seminare/$slug'
      preLoaderRoute: typeof LeistungenSeminareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/seminare/fuehren-mit-zielen': {
      id: '/leistungen/seminare/fuehren-mit-zielen'
      path: '/leistungen/seminare/fuehren-mit-zielen'
      fullPath: '/leistungen/seminare/fuehren-mit-zielen'
      preLoaderRoute: typeof LeistungenSeminareFuehrenMitZielenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/seminare/kraft-der-wertschaetzung': {
      id: '/leistungen/seminare/kraft-der-wertschaetzung'
      path: '/leistungen/seminare/kraft-der-wertschaetzung'
      fullPath: '/leistungen/seminare/kraft-der-wertschaetzung'
      preLoaderRoute: typeof LeistungenSeminareKraftDerWertschaetzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/seminare/moderation-workshops': {
      id: '/leistungen/seminare/moderation-workshops'
      path: '/leistungen/seminare/moderation-workshops'
      fullPath: '/leistungen/seminare/moderation-workshops'
      preLoaderRoute: typeof LeistungenSeminareModerationWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/seminare/zeit-effektivitaet': {
      id: '/leistungen/seminare/zeit-effektivitaet'
      path: '/leistungen/seminare/zeit-effektivitaet'
      fullPath: '/leistungen/seminare/zeit-effektivitaet'
      preLoaderRoute: typeof LeistungenSeminareZeitEffektivitaetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verwaltung/teilnehmer/$terminId': {
      id: '/_authenticated/verwaltung/teilnehmer/$terminId'
      path: '/verwaltung/teilnehmer/$terminId'
      fullPath: '/verwaltung/teilnehmer/$terminId'
      preLoaderRoute: typeof AuthenticatedVerwaltungTeilnehmerTerminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedVerwaltungAnfragenRoute: typeof AuthenticatedVerwaltungAnfragenRoute
  AuthenticatedVerwaltungAnmeldungenRoute: typeof AuthenticatedVerwaltungAnmeldungenRoute
  AuthenticatedVerwaltungTermineRoute: typeof AuthenticatedVerwaltungTermineRoute
  AuthenticatedVerwaltungIndexRoute: typeof AuthenticatedVerwaltungIndexRoute
  AuthenticatedVerwaltungTeilnehmerTerminIdRoute: typeof AuthenticatedVerwaltungTeilnehmerTerminIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedVerwaltungAnfragenRoute: AuthenticatedVerwaltungAnfragenRoute,
  AuthenticatedVerwaltungAnmeldungenRoute:
    AuthenticatedVerwaltungAnmeldungenRoute,
  AuthenticatedVerwaltungTermineRoute: AuthenticatedVerwaltungTermineRoute,
  AuthenticatedVerwaltungIndexRoute: AuthenticatedVerwaltungIndexRoute,
  AuthenticatedVerwaltungTeilnehmerTerminIdRoute:
    AuthenticatedVerwaltungTeilnehmerTerminIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AnfahrtRoute: AnfahrtRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  HonorareRoute: HonorareRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeitfaedenRoute: LeitfaedenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberMichRoute: UeberMichRoute,
  LeistungenBeratungRoute: LeistungenBeratungRoute,
  LeistungenInhouseRoute: LeistungenInhouseRoute,
  LeistungenKonzepteRoute: LeistungenKonzepteRoute,
  LeistungenTalkRoute: LeistungenTalkRoute,
  PraxisbriefAbmeldenRoute: PraxisbriefAbmeldenRoute,
  PraxisbriefBestaetigenRoute: PraxisbriefBestaetigenRoute,
  PraxisbriefeSlugRoute: PraxisbriefeSlugRoute,
  SeminareTermineRoute: SeminareTermineRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
  PraxisbriefeIndexRoute: PraxisbriefeIndexRoute,
  LeistungenSeminareSlugRoute: LeistungenSeminareSlugRoute,
  LeistungenSeminareFuehrenMitZielenRoute:
    LeistungenSeminareFuehrenMitZielenRoute,
  LeistungenSeminareKraftDerWertschaetzungRoute:
    LeistungenSeminareKraftDerWertschaetzungRoute,
  LeistungenSeminareModerationWorkshopsRoute:
    LeistungenSeminareModerationWorkshopsRoute,
  LeistungenSeminareZeitEffektivitaetRoute:
    LeistungenSeminareZeitEffektivitaetRoute,
  LeistungenSeminareIndexRoute: LeistungenSeminareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
